
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./PRIVATE/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config 
  wg-easy:
    environment:
      - LANG=en
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_POST_UP=
          iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; 
          iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
          iptables -A FORWARD -i wg0 -j ACCEPT; 
          iptables -A FORWARD -o wg0 -j ACCEPT;
          iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 9735 -j DNAT --to-destination 10.8.0.2:9735;
          iptables -A FORWARD -i eth0 -o wg0 -p tcp --dport 9735 -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT;
      - WG_POST_DOWN=
          iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;
          iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT;
          iptables -D FORWARD -i wg0 -j ACCEPT; 
          iptables -D FORWARD -o wg0 -j ACCEPT;
          iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 9735 -j DNAT --to-destination 10.8.0.2:9735;
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 
    image: ghcr.io/wg-easy/wg-easy:13
    env_file:
      - ./PRIVATE/private.env
    container_name: wg-easy
    volumes:
      - type: bind
        source: ./etc_wireguard
        target: /etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "9735:9735/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  caddy_data:
  caddy_config:
