services:
  watch_backups:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 watch_backups.py"
      env_file:
        - ./PRIVATE/secrets.env
  send-node-status-to-queue:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 src/send-node-status.py"
      env_file:
        - ./PRIVATE/secrets.env
 