version: '3'

services:
  pworker:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
       
      command: >
              sh -c "python3 watch_backups.py"
      env_file:
        - ../../secrets.env