version: '3'

services:
  pworker:
      user: "1000:1000"
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: ./start.sh
      env_file:
        - ../../secrets.env