version: '3'

services:
  pworker:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 watch_backups.py"
      env_file:
        - ../../secrets.env
      network_mode: 'host'
 