version: '3'

services:
  watch_backups:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 watch_backups.py"
      env_file:
        - ../../secrets.env
  upmonitor:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 src/megalith-upmonitor.py"
      env_file:
        - ../../secrets.env
  lnd_folder_backup:
      user: "1000:1000"
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /workspace/lightning/pworker
        - type: bind
          source: ..
          target: /workspace/lightning
      command: >
              sh -c "python3 src/backup_lnd_folder_to_s3.py"
      env_file:
        - ../../secrets.env