services:
  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    command: "ls"
    user: 1000:1000
    volumes:
      - type: bind
        source: ./lnd-data
        target: /data/.lnd
      - type: bind
        source: ./PRIVATE/lnd-watchtower.conf
        target: /data/.lnd/lnd.conf
      - type: bind
        source: ./PRIVATE
        target: /PRIVATE
      - type: bind
        source: .
        target: /lnd_folder_root
      - type: bind
        source: ../tmp
        target: /tmp
    environment:
      HOME: /data
    network_mode: host
