services:
  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    command: "ls"
    user: 1000:1000
    volumes:
      - type: bind
        source: ./lnd-data
        target: /data/.lnd
      - type: bind
        source: ./PRIVATE/lnd.conf
        target: /data/.lnd/lnd.conf
      - type: bind
        source: .
        target: /lnd_folder_root
      - type: bind
        source: ../tmp
        target: /tmp
    environment:
      HOME: /data
      EXTERNAL_IP: 0
      SKIP_PROXY_FOR_CLEARNET_TARGETS: false
      LISTEN: 0
    network_mode: host
    
